### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by aykl**

### CODE REVIEW

**Review by gijskant — APPROVED** [review]

**Comment by gijskant** [comment]
Since you're working on password validation, the password requirements are listed here: [PasswordValidator.java](https://github.com/thehyve/podium/blob/dev/podium-uaa/src/main/java/nl/thehyve/podium/validation/PasswordValidator.java)
- Length between 8 and 1000
- at least one numerical
- at least one alphabetical
- at least one special chars (non-numerical and non-alphabetical)

Also the matching of the password confirmation is currently not working.

**Comment by gijskant** [comment]
Looks like in the registration form, the green colour, indicating valid required fields, has disappeared:
Registration form validation
Looks like the colour is there when you add the `required` property on the inputs in the template. Strangs that Angular behaves differently when you add `Validators.required` in the form controls than when `required` is specified in the template...

**Comment by aykl** [comment]
> Strangs that Angular behaves differently when you add `Validators.required` in the form controls than when `required` is specified in the template...

I see why it happens: the green mark is defined in CSS via the `.ng-valid[required]` selector, so it depends on the attribute.
It might be possible to drop `Validators.required` in the component code and rely on the built-in https://angular.io/api/forms/RequiredValidator

**Comment by aykl** [comment]
`newpassword.maxlength` and `newpassword.minlength` messages removed since they are already covered by more general `newpassword.requirements`.

**Comment by gijskant** [comment]
> `newpassword.maxlength` and `newpassword.minlength` messages removed since they are already covered by more general `newpassword.requirements`.

I don't think 'maxlength' is covered by that one, but 'required' is. See the suggested changes in #330.

**Review by gijskant — APPROVED** [review]

**Pull request merged**
